# -*- coding: utf-8 -*-
"""NIDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15adwmRexzNXqDOtsIXJQXsPva-_JVdvO

STEP 1  — Dataset Loading
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/CICIDS2017.csv')
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns)

print("\nLabel column value counts:")
print(df["Attack Type"].value_counts().head())

"""STEP 2: Separate Features and Label"""

# Separate features and label
X = df.drop(columns=["Attack Type"])
y = df["Attack Type"]

# Verify separation
print("Features shape (X):", X.shape)
print("Labels shape (y):", y.shape)

print("\nFirst 5 labels:")
print(y.head())

"""STEP 3: Label Grouping (Multi-Class Strategy)"""

label_mapping = {
    "Normal Traffic": "BENIGN",
    "DoS": "FLOODING",
    "DDoS": "FLOODING",
    "Port Scanning": "SCANNING",
    "Brute Force": "BRUTE_FORCE",
    "Web Attacks": "WEB_ATTACK",
    "Bots": "BOTNET"
}

# Apply label grouping
y_grouped = y.map(label_mapping)

# Verify grouped labels
print("Grouped label value counts:")
print(y_grouped.value_counts())

# Safety check (must be empty)
print("\nUnmapped labels (should be empty):")
print(y[y_grouped.isna()].unique())

"""STEP 4  — Data Splitting"""

from sklearn.model_selection import train_test_split

# First split: Train (70%) and Temp (30%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y_grouped,
    test_size=0.30,
    stratify=y_grouped,
    random_state=42
)

# Second split: Validation (15%) and Test (15%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

# Verify shapes
print("Training set shape:", X_train.shape, y_train.shape)
print("Validation set shape:", X_val.shape, y_val.shape)
print("Test set shape:", X_test.shape, y_test.shape)

# Verify class distribution
print("\nTraining label distribution:")
print(y_train.value_counts(normalize=True))

"""STEP 5 — Label Encoding"""

from sklearn.preprocessing import LabelEncoder

# Initialize encoder
label_encoder = LabelEncoder()

# Fit ONLY on training labels
y_train_enc = label_encoder.fit_transform(y_train)

# Transform validation and test labels
y_val_enc = label_encoder.transform(y_val)
y_test_enc = label_encoder.transform(y_test)

# Check encoded classes
print("Encoded class mapping:")
for i, cls in enumerate(label_encoder.classes_):
    print(i, "->", cls)

# Check shapes
print("\nEncoded label shapes:")
print("Train:", y_train_enc.shape)
print("Validation:", y_val_enc.shape)
print("Test:", y_test_enc.shape)

"""STEP 6— Feature Scaling"""

from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit ONLY on training features
X_train_scaled = scaler.fit_transform(X_train)

# Apply same transformation to validation and test sets
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Verify shapes
print("Scaled feature shapes:")
print("Train:", X_train_scaled.shape)
print("Validation:", X_val_scaled.shape)
print("Test:", X_test_scaled.shape)

"""STEP 7  — Reshape for LSTM"""

# Reshape scaled features for LSTM input
# New shape: (samples, timesteps, features)

X_train_lstm = X_train_scaled.reshape(
    X_train_scaled.shape[0], 1, X_train_scaled.shape[1]
)

X_val_lstm = X_val_scaled.reshape(
    X_val_scaled.shape[0], 1, X_val_scaled.shape[1]
)

X_test_lstm = X_test_scaled.reshape(
    X_test_scaled.shape[0], 1, X_test_scaled.shape[1]
)

# Verify shapes
print("LSTM input shapes:")
print("Train:", X_train_lstm.shape)
print("Validation:", X_val_lstm.shape)
print("Test:", X_test_lstm.shape)

"""STEP 8 — Model Definition & Compilation"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Number of classes after Option B grouping
num_classes = len(label_encoder.classes_)

# Build the LSTM model
model = Sequential()

# LSTM layer 1
model.add(
    LSTM(
        units=64,
        return_sequences=True,
        input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])
    )
)
model.add(Dropout(0.3))

# LSTM layer 2
model.add(
    LSTM(
        units=32,
        return_sequences=False
    )
)
model.add(Dropout(0.3))

# Fully connected layer
model.add(Dense(32, activation="relu"))
model.add(Dropout(0.2))

# Output layer (multi-class)
model.add(Dense(num_classes, activation="softmax"))

# Compile the model
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Model summary
model.summary()

"""STEP 9  — Model Training"""

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Compute class weights from training labels
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train_enc),
    y=y_train_enc
)

class_weight_dict = dict(enumerate(class_weights))
print("Class weights:", class_weight_dict)

# Train the model
history = model.fit(
    X_train_lstm,
    y_train_enc,
    validation_data=(X_val_lstm, y_val_enc),
    epochs=5,
    batch_size=512,
    class_weight=class_weight_dict,
    verbose=1
)

"""STEP 10: Model Evaluation

1️⃣ First: Evaluate on Test Set (Overall Performance)
"""

# Evaluate model on test data
test_loss, test_accuracy = model.evaluate(
    X_test_lstm,
    y_test_enc,
    verbose=1
)

print("Test Accuracy:", test_accuracy)
print("Test Loss:", test_loss)

"""2️⃣ Generate Predictions on Test Data"""

import numpy as np

# Predict class probabilities
y_pred_probs = model.predict(X_test_lstm)

# Convert probabilities → class index
y_pred_enc = np.argmax(y_pred_probs, axis=1)
from sklearn.metrics import confusion_matrix
import pandas as pd

# Compute confusion matrix
cm = confusion_matrix(y_test_enc, y_pred_enc)

# Convert to DataFrame for readability
cm_df = pd.DataFrame(
    cm,
    index=label_encoder.classes_,
    columns=label_encoder.classes_
)

print("Confusion Matrix:")
print(cm_df)

"""3️⃣ Classification Report (Per-Class Metrics)"""

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test_enc,
        y_pred_enc,
        target_names=label_encoder.classes_
    )
)

"""STEP 11: Attack Explanation & Alert Logic

1️⃣ Define Feature-Based Rules
"""

# Feature-based explanation rules for each attack type

ATTACK_RULES = {
    "FLOODING": {
        "features": [
            "Flow Packets/s",
            "Flow Bytes/s",
            "Flow IAT Mean",
            "Flow Duration"
        ],
        "reason": (
            "Extremely high packet and byte rates with very short inter-arrival times, "
            "indicating flooding behavior typical of DoS/DDoS attacks."
        ),
        "severity": "HIGH"
    },

    "SCANNING": {
        "features": [
            "Destination Port",
            "Flow Duration",
            "Total Fwd Packets"
        ],
        "reason": (
            "Multiple short-lived connections targeting different ports, "
            "consistent with port scanning activity."
        ),
        "severity": "MEDIUM"
    },

    "BOTNET": {
        "features": [
            "Flow IAT Mean",
            "Active Mean",
            "Idle Mean"
        ],
        "reason": (
            "Regular and automated communication patterns with periodic idle-active cycles, "
            "suggesting botnet command-and-control behavior."
        ),
        "severity": "CRITICAL"
    },

    "BRUTE_FORCE": {
        "features": [
            "Total Fwd Packets",
            "Flow Duration",
            "Flow Packets/s"
        ],
        "reason": (
            "Repeated connection attempts within a short duration, "
            "indicative of brute-force authentication attacks."
        ),
        "severity": "HIGH"
    },

    "WEB_ATTACK": {
        "features": [
            "Packet Length Mean",
            "Packet Length Variance",
            "Flow Duration"
        ],
        "reason": (
            "Abnormal packet size patterns and irregular timing, "
            "consistent with application-layer web attacks."
        ),
        "severity": "HIGH"
    },

    "BENIGN": {
        "features": [],
        "reason": (
            "Traffic behavior is consistent with normal network activity "
            "and does not exhibit malicious characteristics."
        ),
        "severity": "LOW"
    }
}

"""2️⃣ Explanation Generator Function"""

def generate_attack_explanation(
    predicted_label,
    confidence,
    original_features_row
):
    rule = ATTACK_RULES.get(predicted_label, None)

    if rule is None:
        return {
            "attack": predicted_label,
            "confidence": round(float(confidence), 3),
            "severity": "UNKNOWN",
            "reason": "No explanation rule available."
        }

    feature_values = {}
    for feat in rule["features"]:
        if feat in original_features_row:
            feature_values[feat] = float(round(original_features_row[feat], 3))

    return {
        "attack": predicted_label,
        "confidence": round(float(confidence), 3),
        "severity": rule["severity"],
        "reason": rule["reason"],
        "key_features": feature_values
    }

# Example: explain the first test sample

sample_index = 0

predicted_class_index = y_pred_enc[sample_index]
predicted_label = label_encoder.inverse_transform(
    [predicted_class_index]
)[0]

confidence = y_pred_probs[sample_index][predicted_class_index]

# IMPORTANT: use original (unscaled) features
original_row = X_test.iloc[sample_index]

explanation = generate_attack_explanation(
    predicted_label,
    confidence,
    original_row
)

explanation

import numpy as np

# Find a non-BENIGN sample
benign_index = label_encoder.transform(["BENIGN"])[0]

attack_index = np.where(y_test_enc != benign_index)[0][0]

predicted_class_index = y_pred_enc[attack_index]
predicted_label = label_encoder.inverse_transform([predicted_class_index])[0]
confidence = float(y_pred_probs[attack_index][predicted_class_index])

# IMPORTANT: use original (unscaled) features
original_row = X_test.iloc[attack_index]

generate_attack_explanation(
    predicted_label,
    confidence,
    original_row
)

"""STEP 12: Save the Trained Model, Scaler, and Label Encoder"""

# Save the trained LSTM model
model.save("nids_lstm_model.keras")

"""2️⃣ Save the Scaler and Label Encoder"""

import joblib

# Save the scaler
joblib.dump(scaler, "nids_scaler.pkl")

# Save the label encoder
joblib.dump(label_encoder, "nids_label_encoder.pkl")

"""3️⃣ Verify Saved Files"""

import os

print("Saved files:")
for f in os.listdir():
    if "nids" in f:
        print(f)

"""STEP 13: Offline Inference Pipeline (Using Saved Files)"""

from tensorflow.keras.models import load_model
import joblib

# Load saved model
model = load_model("nids_lstm_model.keras")

# Load scaler and label encoder
scaler = joblib.load("nids_scaler.pkl")
label_encoder = joblib.load("nids_label_encoder.pkl")

print("Artifacts loaded successfully.")

import numpy as np

# Select a few unseen samples (simulate new traffic)
sample_indices = [0, 10, 50]

X_new = X_test.iloc[sample_indices]        # original features (unscaled)
X_new_scaled = scaler.transform(X_new)     # scale using saved scaler

# Reshape for LSTM
X_new_lstm = X_new_scaled.reshape(
    X_new_scaled.shape[0], 1, X_new_scaled.shape[1]
)

print("Inference input shape:", X_new_lstm.shape)

# Predict probabilities
y_new_probs = model.predict(X_new_lstm)

# Convert to class indices
y_new_pred_enc = np.argmax(y_new_probs, axis=1)

# Decode labels
y_new_pred_labels = label_encoder.inverse_transform(y_new_pred_enc)

y_new_pred_labels

# Generate explanations for each new sample

results = []

for i, idx in enumerate(sample_indices):
    predicted_label = y_new_pred_labels[i]
    confidence = float(y_new_probs[i][y_new_pred_enc[i]])
    original_row = X_test.iloc[idx]

    explanation = generate_attack_explanation(
        predicted_label,
        confidence,
        original_row
    )

    results.append(explanation)

results